export enum Collection {
  physicalTraining = 'physicalTraining',
  trainingLog = 'trainingLog',
  specsheet = 'specsheet',
  users = 'users',
  arrow = 'arrow',
  arrowRest = 'arrowRest',
  compoundSight = 'compoundSight',
  sightRecurve = 'sightRecurve',
  stringCompound = 'stringCompound',
  stabs = 'stabs',
  plunger = 'plunger',
  release = 'release',
  barbowRecurveBowConfiguration = 'barbowRecurveBowConfiguration',
  compoundConfig = 'compoundConfig',
  fingerLap = 'fingerLap',
  stringRecurveBarbow = 'stringRecurveBarbow',
  scoring = 'scoring',
  goal = 'goal'
}
